GET http://{{server}}:{{port}}/api/v1/
Accept: application/json

###

POST http://{{server}}:{{port}}/api/v1/shopping-lists
Content-Type: application/json

{
  "name": "{{shoppingListName}} {{$randomInt}}"
}

###

GET http://{{server}}:{{port}}/api/v1/shopping-lists
Accept: application/json

###

GET http://{{server}}:{{port}}/api/v1/shopping-lists/{{shoppingListId}}
Accept: application/json

###

GET http://{{server}}:{{port}}/api/v1/shopping-lists/{{shoppingListId}}/items
Accept: application/json

###

POST http://{{server}}:{{port}}/api/v1/shopping-lists/{{shoppingListId}}/items
Content-Type: application/json

{
  "name": "Buy milk"
}

###

PUT http://{{server}}:{{port}}/api/v1/shopping-lists/{{shoppingListId}}/items/{{listItemId}}
Content-Type: application/json

{
  "name": "Buy milk {{$randomInt}}",
  "status": "DONE"
}

###

DELETE http://{{server}}:{{port}}/api/v1/shopping-lists/{{shoppingListId}}/items/{{listItemId}}
Content-Type: application/json

###