GET http://{{server}}:{{port}}/api/v1/
Accept: application/json

###

POST http://{{server}}:{{port}}/api/v1/shopping-lists/
Content-Type: application/json

{
  "name": "{{shoppingListName}} {{$randomInt}}"
}

###

GET http://{{server}}:{{port}}/api/v1/shopping-lists/
Accept: application/json

###

GET http://{{server}}:{{port}}/api/v1/shopping-lists/609edfa800be9b9000e94929
Accept: application/json

###
